### ISSUE TITLE
data/parsedRepos/meta is NOT found

### ISSUE THREAD

**Issue by XujieSi** [MrVPlusOne/LambdaNet#4]
Hello,

Thanks a lot for sharing the ICLR'20 artifacts! 

We tried to rerun the pretrained model using docker, but unfortunately got the following error:
```
[error] Exception in thread "main" java.io.FileNotFoundException: /usr/src/lambdanet/data/parsedRepos/meta (No such file or directory)
[error] 	at java.base/java.io.FileInputStream.open0(Native Method)
[error] 	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
[error] 	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
[error] 	at funcdiff.SimpleMath$$anon$1.<init>(SimpleMath.scala:507)
[error] 	at funcdiff.SimpleMath$.readObjectFromFile(SimpleMath.scala:507)
[error] 	at lambdanet.PrepareRepos$ParsedRepos$.readFromDir(PrepareRepos.scala:392)
[error] 	at lambdanet.RunTrainedModel$.runTrainedModel(RunTrainedModel.scala:32)
[error] 	at lambdanet.RunTrainedModel$.main(RunTrainedModel.scala:157)
[error] 	at lambdanet.RunTrainedModel.main(RunTrainedModel.scala)
[error] Nonzero exit code returned from runner: 1
[error] (Compile / runMain) Nonzero exit code returned from runner: 1
[error] Total time: 42 s, completed Aug 20, 2020, 3:43:10 PM
```

Any idea to resolve this?

BTW, it is awesome to see that the implementation is done in Scala!

**Comment by MrVPlusOne** [comment]
Hi,

Yes, please download the parsed repos file using [this link](https://drive.google.com/file/d/1ZhsUf9bUzT3ZJB0KzNP6w2aj3sQZwtsp/view?usp=sharing), unzip the directory, and then put it under the `data` directory. We now also provide an alternative way to run the pre-trained model, which outputs `(source file position, predicted type)` pairs instead of HTML files. I will update the README instructions shortly!
